version: '3.8'
services:

    nginx:
        image: nginx:latest
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./htdocs:/var/www
            - ./hosts:/etc/nginx/conf.d
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php
        ports:
            - "8080:80"

    php:
        build: ./images/php
        volumes:
            - ./config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
            - ./htdocs:/var/www

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: superpass
            MYSQL_USER:          user
            MYSQL_PASSWORD:      password
            MYSQL_DATABASE:      MyDB
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=password
        ports:
            - 8090:80
